In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
x = Series([1,2,3,4])

In [3]:
x

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
x.values

array([1, 2, 3, 4])

In [5]:
x.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
y = Series([1,2,3], index=['a', 'b', 'c'])

In [7]:
y

a    1
b    2
c    3
dtype: int64

In [8]:
y.index

Index([u'a', u'b', u'c'], dtype='object')

In [9]:
y['a']

1

In [10]:
y['d'] = 6

In [11]:
y

a    1
b    2
c    3
d    6
dtype: int64

In [12]:
y[['a','b']]

a    1
b    2
dtype: int64

In [13]:
y[y>2]

c    3
d    6
dtype: int64

In [14]:
y * 2

a     2
b     4
c     6
d    12
dtype: int64

In [15]:
y

a    1
b    2
c    3
d    6
dtype: int64

In [16]:
d = {'x':9, 'y':8}

In [17]:
x = Series(d)

In [18]:
x

x    9
y    8
dtype: int64

In [19]:
x = Series(d, index=['x', 'z'])

In [20]:
x

x    9.0
z    NaN
dtype: float64

In [21]:
pd.isnull(x)

x    False
z     True
dtype: bool

In [22]:
x.isnull()

x    False
z     True
dtype: bool

In [23]:
y

a    1
b    2
c    3
d    6
dtype: int64

In [24]:
x

x    9.0
z    NaN
dtype: float64

In [25]:
x['a'] = 5
x['b'] = 6

In [26]:
x + y

a    6.0
b    8.0
c    NaN
d    NaN
x    NaN
z    NaN
dtype: float64

In [27]:
x

x    9.0
z    NaN
a    5.0
b    6.0
dtype: float64

In [28]:
y

a    1
b    2
c    3
d    6
dtype: int64

In [29]:
y.name='teste'

In [30]:
y.index.name='iteste'

In [31]:
y

iteste
a    1
b    2
c    3
d    6
Name: teste, dtype: int64

In [32]:
y.index = [9,8,7,6]

In [33]:
y

9    1
8    2
7    3
6    6
Name: teste, dtype: int64

In [34]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada', 'Nevada'], 'year':[2000,2001,2002,2001,2002], 'pop':[1.5,1.7,3.6,2.4,2.9]}

In [35]:
frame = DataFrame(data, columns=['year','state', 'pop'])

In [36]:
frame

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [37]:
frame2 = DataFrame(data, columns=['year','state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [38]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [39]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [40]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [41]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 10

In [43]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5    10
two    2001    Ohio  1.7    10
three  2002    Ohio  3.6    10
four   2001  Nevada  2.4    10
five   2002  Nevada  2.9    10

In [44]:
frame2['debt'] = range(0,5)

In [45]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [46]:
val = Series([1.2,1.5,1.7], index=['two', 'four', 'five'])

In [47]:
frame2['debt'] = val

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9   1.7

In [49]:
frame2['eastern'] = frame2.state == 'Ohio'

In [50]:
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7   1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4   1.5   False
five   2002  Nevada  2.9   1.7   False

In [51]:
del frame2['eastern']

In [52]:
frame2.T

one   two three    four    five
year   2000  2001  2002    2001    2002
state  Ohio  Ohio  Ohio  Nevada  Nevada
pop     1.5   1.7   3.6     2.4     2.9
debt    NaN   1.2   NaN     1.5     1.7

In [53]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, 1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, 1.5],
       [2002, 'Nevada', 2.9, 1.7]], dtype=object)

In [54]:
frame2.index

Index([u'one', u'two', u'three', u'four', u'five'], dtype='object')

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9   1.7

In [56]:
vals = frame2.values

In [57]:
inds = frame2.index

In [58]:
frame3 = DataFrame(vals, index=inds)

In [59]:
frame3

0       1    2    3
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  1.2
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  1.5
five   2002  Nevada  2.9  1.7

In [60]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [61]:
frame3.columns = frame2.columns

In [62]:
frame3

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  1.2
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  1.5
five   2002  Nevada  2.9  1.7

In [63]:
frame3

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  1.2
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  1.5
five   2002  Nevada  2.9  1.7

In [64]:
'state' in frame3.columns

True

In [65]:
obj = Series([4,7,-5,3], index='d,b,a,c'.split(','))

In [66]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [67]:
obj2 = obj.reindex(['a,b,c,d,e'.split(',')])

In [68]:
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

obj.reindex(['a,b,c,d,e'.split(',')], fill_value=0)

In [69]:
obj.reindex(['a,b,c,d,e'.split(',')], fill_value=0)

a   -5
b    7
c    3
d    4
e    0
dtype: int64

In [70]:
obj3 = Series(['azul', 'verde', 'preto'], index=[0,1,5])

In [71]:
obj3.reindex(range(6), method='ffill')

0     azul
1    verde
2    verde
3    verde
4    verde
5    preto
dtype: object

In [72]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'], columns=['Ohio', 'Texas', 'Calif'])

NameError: name 'np' is not defined

In [73]:
import numpy as np

In [74]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
frame

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [77]:
frame.reindex(['a','b','c','d'])

year state  pop
a   NaN   NaN  NaN
b   NaN   NaN  NaN
c   NaN   NaN  NaN
d   NaN   NaN  NaN

In [78]:
frame.reindex(columns=['Texas', 'Utah', 'Calif'])

Texas  Utah  Calif
0    NaN   NaN    NaN
1    NaN   NaN    NaN
2    NaN   NaN    NaN
3    NaN   NaN    NaN
4    NaN   NaN    NaN

In [79]:
frame.ix

In [80]:
frame.ix[['a','b','c','d'], ['Texas', 'Utah', 'Calif']]

Texas  Utah  Calif
a    NaN   NaN    NaN
b    NaN   NaN    NaN
c    NaN   NaN    NaN
d    NaN   NaN    NaN

In [81]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [82]:
obj.drop('a')

d    4
b    7
c    3
dtype: int64

In [83]:
obj.drop(['a','b'])

d    4
c    3
dtype: int64

In [84]:
frame

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [85]:
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [86]:
obj['b']

7

In [87]:
obj[2:3]

a   -5
dtype: int64

In [88]:
obj[['a','b']]

a   -5
b    7
dtype: int64

In [89]:
obj[obj > 0]

d    4
b    7
c    3
dtype: int64

In [92]:
obj['a':'c'] = 1

In [93]:
frame

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [94]:
frame['year']

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

In [95]:
frame[:2]

year state  pop
0  2000  Ohio  1.5
1  2001  Ohio  1.7

In [96]:
frame[frame['year']>2000]

year   state  pop
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [98]:
frame >2000

year state    pop
0  False  True  False
1   True  True  False
2   True  True  False
3   True  True  False
4   True  True  False

In [99]:
frame.ix[1, ['state', 'pop']]

state    Ohio
pop       1.7
Name: 1, dtype: object

In [100]:
frame.ix[:1, ['state', 'pop']]

state  pop
0  Ohio  1.5
1  Ohio  1.7

In [101]:
frame.ix[[3,0], ['state', 'pop']]

state  pop
3  Nevada  2.4
0    Ohio  1.5